directory: /mnt/Media/Music
library: /mnt/Media/Music/musiclibrary.db

import:
    move: yes
    incremental: yes
    #incremental_skip_later: yes
    language: en ru

clutter: ["*.log", "*.cue", "*.jpg", "*.png", "*.pdf", "*.txt", "Scans", "scans", "Artwork"]

plugins: unimported ipfs check chroma

unimported:
    ignore_subdirectories: UNIMPORTED
    ignore_extensions: db

ipfs:
    nocopy: true
    auto: no

check:
  import: yes
  write-check: yes
  write-update: yes
  convert-update: yes
  threads: 4
