---
template:
  direction: Horizontal
  parts:
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 1
      run:
        plugin:
          location: "zellij:tab-bar"
    - direction: Vertical
      body: true
    - direction: Vertical
      borderless: true
      split_size:
        Fixed: 2
      run:
        plugin:
          location: "zellij:status-bar"
tabs:
  - name: "zsh"
  - name: "zsh"
  - name: "solcery"
    run:
      command: {cmd: zsh, args: ["-c", "cd ~/Documents/Repo/solcery/on-chain && zsh"]}
  - name: "solcery build"
    run:
      command: {cmd: zsh, args: ["-c", "cd ~/Documents/Repo/solcery/on-chain && zsh"]}
