[helpers]

[default]
depends = [
	"alacritty",
	"cargo",
	"earbuds",
	"git",
	"paru",
	"pueue",
	"starship",
	"vim",
	"zathura",
	"zellij",
	"zsh",
]

[root]
depends = [
	"ssh",
	"pacman",
]

[zathura.files]
zathura = "~/.config/zathura"

[zellij.files]
zellij = "~/.config/zellij"

[alacritty.files]
alacritty = "~/.config/alacritty"

[paru.files]
paru = "~/.config/paru"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"

[cargo.files]
cargo = "~/.cargo"

[vim.files]
vim = "~/.vim"

[pueue.files]
pueue = "~/.config/pueue"

[borg.files]
"borg/backup.sh" = "~/.local/bin/backup.sh"
"borg/exclusions" = "~/.borg/exclusions"

[ssh.files]
ssh = {target = "/etc/ssh", type = "template", owner = "root"}

[git.files]
"git/config" = "~/.gitconfig"

[pacman.files]
"pacman/pacman.conf" = {target = "/etc/pacman.conf", type = "template", owner = "root"}

[i3]
depends = ["betterlockscreen", "i3status-rs"]

[i3.files]
i3 = "~/.config/i3"

[Xorg.files]
"Xorg/Xresources" = "~/.Xresources"
"Xorg/input" = {target = "/usr/share/X11/xorg.conf.d/40-libinput.conf", type = "template", owner = "root"}
"Xorg/monitor" = {target = "/etc/X11/xorg.conf.d/40-monitor.conf", type = "template", owner = "root", if = '(eq (command_output "hostname") "Main-pc\n")'}

[mpd]
depends = ["mpdas"]

[mpd.files]
mpd = "~/.config/mpd"

[mpdas.files]
"mpdas/mpdasrc" = "~/.config/mpdasrc"

[transmission.files]
transmission = "~/.config/transmission-daemon"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[earbuds.files]
earbuds = "~/.config/livebuds"

[betterlockscreen.files]
betterlockscreen = "~/.config"

[i3status-rs.files]
i3status-rs = "~/.config/i3status-rust"
