[helpers]

[default]
depends = [
	"alacritty",
	"cargo",
	"paru",
	"pueue",
	"vim",
	"zathura",
	"zellij",
]

[zathura.files]
zathura = "~/.config/zathura"

[zellij.files]
zellij = "~/.config/zellij"

[alacritty.files]
alacritty = "~/.config/alacritty"

[paru.files]
paru = "~/.config/paru"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"

[cargo.files]
cargo = "~/.cargo"

[vim.files]
vim = "~/.vim"

[pueue.files]
pueue = "~/.config/pueue"

[borg.files]
"borg/backup.sh" = "~/backup.sh"
"borg/exclusions" = "~/.borg/exclusions"
