[helpers]

[default]
depends = [
	"alacritty",
	"cargo",
	"ctags",
	"earbuds",
	"git",
	"paru",
	"pueue",
	"starship",
	"vim",
	"zathura",
	"zellij",
	"zsh",
]

[root]
depends = [
	"ssh",
	"pacman",
]

[zathura.files]
zathura = "~/.config/zathura"

[zellij.files]
zellij = "~/.config/zellij"

[alacritty.files]
alacritty = "~/.config/alacritty"

[paru.files]
paru = "~/.config/paru"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"
"zsh/plugins" = "~/.zsh/plugins"
"zsh/command-not-found.zsh" = "~/.zsh/command-not-found.zsh"
"zsh/manjaro-zsh-config" = "~/.zsh/manjaro-zsh-config"

[cargo.files]
cargo = "~/.cargo"

[vim.files]
vim = "~/.vim"

[pueue.files]
pueue = "~/.config/pueue"

[borg.files]
"borg/backup.sh" = "~/.local/bin/backup.sh"
"borg/ThinkPad.sh" = {target = "~/.local/bin/ThinkPad.sh", type = "template", if = '(eq (command_output "hostname") "BackupStick\n")'}
"borg/Main-pc.sh" = {target = "~/.local/bin/Main-pc.sh", type = "template", if = '(eq (command_output "hostname") "BackupStick\n")'}
"borg/Triana.sh" = {target = "~/.local/bin/Triana.sh", type = "template", if = '(eq (command_output "hostname") "BackupStick\n")'}
"borg/exclusions" = "~/.borg/exclusions"

[ssh.files]
"ssh/sshd_config" = {target = "/etc/ssh/sshd_config", type = "template", owner = "root"}
"ssh/ssh_config" = "~/.ssh/config"

[git.files]
"git/config" = "~/.gitconfig"

[pacman.files]
"pacman/pacman.conf" = {target = "/etc/pacman.conf", type = "template", owner = "root"}

[i3]
depends = ["betterlockscreen", "i3status-rs", "rofi"]

[i3.files]
i3 = "~/.config/i3"

[Xorg.files]
"Xorg/Xresources" = "~/.Xresources"
"Xorg/input" = {target = "/etc/X11/xorg.conf.d/40-libinput.conf", type = "template", owner = "root"}
"Xorg/monitor" = {target = "/etc/X11/xorg.conf.d/40-monitor.conf", type = "template", owner = "root", if = '(eq (command_output "hostname") "Main-pc\n")'}
"Xorg/thinkpad" = {target = "/etc/X11/xorg.conf.d/20-thinkpad.conf", type = "template", owner = "root", if = '(eq (command_output "hostname") "ThinkPad\n")'}

[mpd]
depends = ["mpdas", "mpdris2"]

[mpd.files]
mpd = "~/.config/mpd"

[mpdas.files]
"mpdas/mpdasrc" = "~/.config/mpdasrc"

[transmission.files]
transmission = "~/.config/transmission-daemon"

[starship.files]
"starship/starship.toml" = "~/.config/starship.toml"

[earbuds.files]
earbuds = "~/.config/livebuds"

[betterlockscreen.files]
betterlockscreen = "~/.config"

[i3status-rs.files]
i3status-rs = "~/.config/i3status-rust"

[rofi.files]
rofi = "~/.config/rofi"

[mpdris2.files]
"mpDris2/mpDris2.conf" = "~/.config/mpDris2/mpDris2.conf"
"mpDris2/mpdris.service" = "~/.config/systemd/user/mpdris.service"

[nu.files]
nu = "~/.config/nushell"

[helix.files]
helix = "~/.config/helix"

[qmk.files]
"qmk/qmk.ini" = "~/.config/qmk/qmk.ini"
"qmk/layouts" = {target = "~/qmk_firmware/keyboards", type = "symbolic"}

[ctags.files]
"ctags/ctags" = "~/.ctags"
