[helpers]

[default]
depends = [
	"alacritty",
	"cargo",
	"git",
	"paru",
	"pueue",
	"vim",
	"zathura",
	"zellij",
	"zsh",
]

[root]
depends = [
	"ssh",
	"pacman",
]

[zathura.files]
zathura = "~/.config/zathura"

[zellij.files]
zellij = "~/.config/zellij"

[alacritty.files]
alacritty = "~/.config/alacritty"

[paru.files]
paru = "~/.config/paru"

[zsh.files]
"zsh/zshrc" = "~/.zshrc"

[cargo.files]
cargo = "~/.cargo"

[vim.files]
vim = "~/.vim"

[pueue.files]
pueue = "~/.config/pueue"

[borg.files]
"borg/backup.sh" = "~/backup.sh"
"borg/exclusions" = "~/.borg/exclusions"

[ssh.files]
ssh = {target = "/etc/ssh", type = "template", owner = "root"}

[git.files]
"git/config" = "~/.gitconfig"

[pacman.files]
"pacman/pacman.conf" = {target = "/etc/pacman.conf", type = "template", owner = "root"}

[i3.files]
i3 = "~/.config/i3"
