[borg.variables]
target = "Borg"
mountpoint = "/mnt/Backup"
backups = "/home/eugene /etc /mnt/Media/Pictures /mnt/Media/Books /mnt/Media/cloud_archive /mnt/Media/Music"

[Xorg.variables]
display = "DVI-0"
dpi = 96
resolution = "1920x1080"
