# Use powerline
#USE_POWERLINE="true"
# Source manjaro-zsh-configuration
if [[ -e ~/.zsh/manjaro-zsh-config ]]; then
  source ~/.zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
#if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
  #source /usr/share/zsh/manjaro-zsh-prompt
#fi

alias cp='xcp'
alias grep='rg'
alias ls='eza'
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='nano -w PKGBUILD'
alias more=less
alias maxima=rmaxima
alias x='gio trash'
alias torrents='watch transmission-remote -t active -l -st'
alias gf='git flow'
umask 022

#pueue
alias pa='pueue add --'
alias pl='pueue log'
alias ps='pueue status'
alias pf='pueue follow'
alias pc='pueue clean'

# screen
#if [[ -z "$STY" ]]; then
   #export TERM=screen-256color
   #screen -xRR autoscreen
#fi

# Zellij
if [[ (-n "$DISPLAY") && (-z "$ZELLIJ") && ("$TERM_PROGRAM" != "vscode") ]]; then
	if zellij -s main
	then
		eval "$(ssh-agent)"
	else
		zellij attach main
	fi
fi

PATH=~/.nix-profile/bin:$PATH:~/.cargo/bin

export EDITOR='vim'
export VISUAL='vim'

{{#if (eq (command_output "hostname") "Main-pc\n")}}
# Main-pc specific
alias torrents='watch transmission-remote -t active -l -st'
{{else}}
# not Main-pc specific

# Main-pc (un)mounting
alias mount-pc='sshfs -p{{port}} 192.168.1.68:/mnt/Media /mnt/Media/' 
alias unmount-pc='umount /mnt/Media'

# Repo syncing
alias sync-from-main='rsync -apgtv --rsh="ssh -p{{port}}" --recursive --exclude ".git" --exclude "target" --exclude "test-ledger" --exclude "corpus" --exclude "coverage" --exclude "artifacts" 192.168.1.68:$(pwd)/ $(pwd)'
alias sync-to-main='rsync -apgtv --rsh="ssh -p{{port}}" --recursive --exclude ".git" --exclude "target"  --exclude "test-ledger" --exclude "corpus" --exclude "coverage" --exclude "artifacts" $(pwd)/ 192.168.1.68:$(pwd)'
{{/if}}
export TERM=xterm-256color-italic

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

alias slm-build='cmake --build ../build-libslm-Desktop-Debug --target all'

export IPFS_PATH=/mnt/Media/ipfs
