# Use powerline
#USE_POWERLINE="true"
# Source manjaro-zsh-configuration
if [[ -e /usr/share/zsh/manjaro-zsh-config ]]; then
  source /usr/share/zsh/manjaro-zsh-config
fi
# Use manjaro zsh prompt
#if [[ -e /usr/share/zsh/manjaro-zsh-prompt ]]; then
  #source /usr/share/zsh/manjaro-zsh-prompt
#fi

alias cp='xcp'
alias grep='rg'
alias ls='exa'
alias df='df -h'                          # human-readable sizes
alias free='free -m'                      # show sizes in MB
alias np='nano -w PKGBUILD'
alias more=less
alias maxima=rmaxima
alias x='gio trash'
umask 027

#pueue
alias pa='pueue add --'
alias pl='pueue log'
alias ps='pueue status'

# screen
#if [[ -z "$STY" ]]; then
   #export TERM=screen-256color
   #screen -xRR autoscreen
#fi
# Zellij
if [[ -z "$ZELLIJ_RUN" ]]; then
	export ZELLIJ_RUN=1234
	if zellij -s main
	then
	else
		zellij attach main
	fi
fi

PATH=$PATH:~/.cargo/bin
PATH="$PATH:/home/eugene/.local/share/solana/install/active_release/bin"

export EDITOR='vim'
export VISUAL='vim'

{{#if (eq (command_output "hostname") "Main-pc\n")}}
# Main-pc specific
alias torrents='watch transmission-remote -t active -l -st'
{{else}}
# not Main-pc specific

# Main-pc (un)mounting
alias mount-pc='sshfs 192.168.1.68:/mnt/Media /mnt/Media/' 
alias unmount-pc='umount /mnt/Media'

# Repo syncing
alias sync-from-main='rsync -apgtv --recursive --exclude ".git" --exclude "target" 192.168.1.68:~/Documents/Repo/solcery/on-chain/ ~/Documents/Repo/solcery/on-chain/'
alias sync-to-main='rsync -apgtv --recursive --exclude ".git" --exclude "target" ~/Documents/Repo/solcery/on-chain/ 192.168.1.68:~/Documents/Repo/solcery/on-chain/'
{{/if}}
export TERM=xterm-256color-italic

eval "$(starship init zsh)"
eval "$(zoxide init zsh)"

alias slm-build='cmake --build ../build-libslm-Desktop-Debug --target all'
