[theme]
theme = "solarized-dark"

[icons]
icons = "awesome6"

[[block]]
block = "music"
format = " $icon {$combo.str(max_w:20) $play $next |}"
[[block.click]]
button = "left"
cmd = "cantata"

[[block]]
block = "memory"
interval = 5
warning_mem = 80
critical_mem = 95
warning_swap = 80
critical_swap = 95
format = " $icon $mem_total_used_percents.eng(w:2) "
format_alt = " $icon_swap $swap_free.eng(w:3,u:B,p:M)/$swap_total.eng(w:3,u:B,p:M)($swap_used_percents.eng(w:2)) "

[[block]]
block = "cpu"
interval = 1

[[block]]
block = "custom"
command = "~/.config/i3status-rust/buds.sh"
json = true
interval = 5
hide_when_empty = true

{{#if (eq (command_output "hostname") "ThinkPad\n")}}
[[block]]
block = "backlight"
device = "intel_backlight"

{{/if}}
[[block]]
block = "sound"

[[block]]
block = "net"
format = " $icon {$signal_strength $ssid |Wired connection}"
format_alt = " $icon ^icon_net_down $speed_down.eng(prefix:K) ^icon_net_up $speed_up.eng(prefix:K) "
[[block.click]]
button = "left"
cmd = "alacritty -e nmtui"
[[block.click]]
button = "right"
action = "toggle_format"
[block.theme_overrides]
idle_fg = { link = "good_fg" }
idle_bg = { link = "good_bg" }

{{#if (eq (command_output "hostname") "ThinkPad\n")}}
[[block]]
block = "battery"
interval = 10
format = " $icon $percentage $time "
full_threshold = 99
info = 60
warning = 30
critical = 15
empty_threshold = 6
[block.theme_overrides]
idle_fg = { link = "good_fg" }
idle_bg = { link = "good_bg" }

{{/if}}
[[block]]
block = "pacman"
interval = 600
format = " $icon $pacman + $aur "
format_singular = " $icon $both "
format_up_to_date = " ok "
critical_updates_regex = "(linux*)"
aur_command = "paru -Qua"

[[block]]
block = "time"
interval = 5
[block.format]
full = " $icon $timestamp.datetime(f:'%a %d/%m %R') "
